import turtle

def turtleLetter(letter,tur):
    if letter=="box":
        tur.setheading(0)
        tur.forward(40)
        tur.right(90)
        tur.forward(60)
        tur.right(90)
        tur.forward(40)
        tur.right(90)
        tur.forward(60)

    elif letter == "A":
        tur.setheading(270)
        tur.pd()
        tur.fd(30)
        tur.right(180)
        tur.fd(30)
        tur.right(90)
        tur.fd(20)
        tur.right(90)
        tur.fd(30)
        tur.right(180)
        tur.fd(15)
        tur.left(90)
        tur.fd(20)
        tur.pu()
        #fixes
        tur.right(90)
        tur.fd(15)
        tur.right(90)
        tur.fd(35)
        #tur.right(180)
        #Oluschi: P, R, I, H, B, O, Z
    elif letter == "B":
        tur.setheading(0)
        tur.pd()
        tur.right(90)
        tur.fd(30)
        tur.left(90)
        tur.fd(20)
        tur.left(90)
        tur.fd(13)
        tur.left(90)
        tur.fd(20)
        tur.right(90)
        tur.fd(4)
        tur.right(90)
        tur.fd(20)
        tur.left(90)
        tur.fd(13)
        tur.left(90)
        tur.fd(20)
        tur.right(180)
        tur.pu()
        tur.fd(35)
	    
    elif letter == "C":
        tur.setheading(0)
        tur.fd(20)
        tur.setheading(180)
        tur.pd()
        tur.fd(20)
        tur.setheading(270)
        tur.fd(30)
        tur.setheading(0)
        tur.fd(20)
        tur.pu()
        tur.setheading(90)
        tur.fd(30)
        tur.setheading(0)
        tur.fd(15)
    elif letter == "D":
        tur.setheading(270)
        tur.pd()
        tur.fd(30)
        tur.setheading(90)
        tur.fd(30)
        tur.setheading(0)
        tur.fd(15)
        tur.setheading(315)
        tur.fd(3)
        tur.setheading(270)
        tur.fd(25)
        tur.setheading(235)
        tur.fd(3)
        tur.setheading(180)
        tur.fd(15)
        tur.pu()
        tur.setheading(90)
        tur.fd(30)
        tur.setheading(0)
        tur.fd(35)
    elif letter == "E":
        tur.pd()
        tur.fd(20)
        tur.pu()
        tur.setheading(180)
        tur.fd(20)
        tur.setheading(270)
        tur.pd()
        tur.fd(15)
        tur.setheading(0)
        tur.fd(20)
        tur.setheading(180)
        tur.fd(20)
        tur.setheading(270)
        tur.fd(15)
        tur.setheading(0)
        tur.fd(20)
        tur.pu()
        tur.right(180)
        tur.fd(15)
        tur.right(90)
        tur.fd(30)
        tur.setheading(0)
        tur.fd(35)
    elif letter == "F":
        tur.pd()
        tur.fd(20)
        tur.pu()
        tur.setheading(180)
        tur.fd(20)
        tur.setheading(270)
        tur.pd()
        tur.fd(15)
        tur.setheading(0)
        tur.fd(20)
        tur.setheading(180)
        tur.fd(20)
        tur.setheading(270)
        tur.fd(15)
        tur.pu()
        tur.right(180)
        tur.fd(30)
        tur.right(90)
        tur.fd(35)
    elif letter == "G":
        tur.setheading(0)
        tur.fd(20)
        tur.setheading(180)
        tur.pd()
        tur.fd(20)
        tur.setheading(270)
        tur.fd(30)
        tur.setheading(0)
        tur.fd(20)
        tur.setheading(90)
        tur.fd(10)
        tur.left(90)
        tur.fd(10)
        tur.pu()
        tur.right(180)
        tur.fd(10)
        tur.left(90)
        tur.fd(20)
        tur.right(90)
        tur.fd(15)		
    elif letter == "H":
	 
        tur.setheading(0)
        tur.pd()
        tur.right(90)
        tur.fd(30)
        tur.right(180)
        tur.fd(15)
        tur.right(90)
        tur.fd(20)
        tur.right(90)
        tur.fd(15)
        tur.right(180)
        tur.fd(30)
        tur.right(90)
        tur.pu()
        tur.fd(15)
    elif letter == "I":
        tur.setheading(0)
        tur.pd()
        tur.fd(20)
        tur.pu()
        tur.right(180)
        tur.fd(10)
        tur.left(90)
        tur.pd()
        tur.fd(30)
        tur.right(90)
        tur.fd(10)
        tur.pu()
        tur.right(180)
        tur.fd(10)
        tur.pd()
        tur.fd(10)
        tur.pu()
        tur.left(90)
        tur.fd(30)
        tur.right(90)
        tur.fd(15)

        
    elif letter == "J":
        tur.setheading(0)
        tur.pd()
        tur.fd(20)
        tur.bk(10)
        tur.right(90)
        tur.fd(30)
        tur.right(90)
        tur.fd(14)
        tur.right(90)
        tur.fd(12)
        #fix
        tur.pu()
        tur.fd(18)
        tur.right(90)
        tur.fd(39)
    elif letter == "K":
	tur.pu()
        tur.right(90)
        tur.pd()
        tur.fd(30)#40
        tur.bk(15)#20
        tur.left(145)
        tur.fd(10)#20
        tur.bk(10)#20
        tur.right(110)
        tur.fd(20)#25
        tur.left(145)
        tur.pu()
        tur.fd(30)
        tur.right(90)
        tur.fd(15)
    elif letter == "L":
        tur.pd()
        tur.right(90)
        tur.fd(30)
        tur.setheading(0)
        tur.fd(20)
        tur.pu()
        tur.setheading(90)
        tur.fd(30)
        tur.setheading(0)
        tur.fd(15)

    elif letter == "M":
	tur.pu()
        tur.right(90)
        tur.pd()
        tur.fd(30)
        tur.bk(30)
        tur.left(20)
        tur.fd(20)
        tur.left(135)
        tur.fd(20)
        tur.right(155)
        tur.fd(30)
        tur.bk(30)
        tur.pu()
        tur.left(90)
        tur.fd(15)
    elif letter == "N":
	tur.pd()
        tur.right(90)
        tur.fd(30)
        tur.bk(30)
        tur.left(30)
        tur.fd(35)
        tur.left(150)
        tur.fd(30)
        tur.pu()
        tur.right(90)
        tur.fd(15)
           
    elif letter == "O":
        tur.setheading(0)
        tur.pd()
        tur.right(90)
        tur.fd(30)
        tur.left(90)
        tur.fd(20)
        tur.left(90)
        tur.fd(30)
        tur.left(90)
        tur.fd(20)
        tur.pu()
        tur.right(180)
        tur.fd(35)
    
    elif letter == "P":
        tur.setheading(0)
        tur.right(90)
        tur.pd()
        tur.fd(30)
        tur.right(180)
        tur.fd(30)
        tur.right(90)
        tur.fd(20)
        tur.right(90)
        tur.fd(15)
        tur.right(90)
        tur.fd(20)
        tur.pu()
        tur.right(90)
        tur.fd(15)
        tur.right(90)
        tur.fd(35)
        #tur.right(180)
        #tur.fd(15)
        #tur.left(90)
        #tur.fd(20)
        #tur.pu()
        #fixes
        #tur.right(90)
        #tur.fd(20)
        #tur.right(90)
        #tur.fd(35)
        #tur.right(180)
        #Oluschi: P, R, I, H, B, O, Z		
    elif letter == "Q":
	tur.pd()
        tur.forward(20)
        tur.right(90)
        tur.forward(30)
        tur.left(30)
        tur.forward(10)
        tur.right(180)
        tur.forward(20)
        tur.left(180)
        tur.forward(10)
        tur.setheading(180)
        tur.forward(20)
        tur.right(90)
        tur.forward(30)
        tur.pu()
        tur.right(90)
        tur.fd(35)
    elif letter == "R":
        tur.setheading(0)
        tur.right(90)
        tur.pd()
        tur.fd(30)
        tur.right(180)
        tur.fd(30)
        tur.right(90)
        tur.fd(20)
        tur.right(90)
        tur.fd(15)
        tur.right(90)
        tur.fd(20)
        tur.left(145)
        tur.fd(28)
        tur.pu()
        tur.left(120)
        tur.fd(32)
        tur.right(90)
        tur.fd(13)

        
        
	    
    elif letter == "S":
        tur.setheading(0)
        tur.pd()
        tur.fd(20)
        tur.pu()
        tur.bk(20)
        tur.right(90)
        tur.pd()
        tur.fd(12)
        tur.left(90)
        tur.fd(20)
        tur.right(90)
        tur.fd(18)
        tur.right(90)
        tur.fd(22)
        #fixes
        tur.pu()
        tur.right(90)
        tur.fd(30)
        tur.right(90)
        tur.fd(37)
    elif letter == "T":
        tur.setheading(0)
        tur.pd()
        tur.fd(20)
        tur.bk(10)
        tur.right(90)
        tur.fd(30)
        #fixes
        tur.pu()
        tur.left(180)
        tur.fd(30)
        tur.right(90)
        tur.fd(25)
    elif letter == "U":
        tur.setheading(270)
        tur.pd()
        tur.fd(30)
        tur.left(90)
        tur.fd(20)
        tur.left(90)
        tur.fd(30)
        #fixes
        tur.pu()
        tur.right(90)
        tur.fd(15)
    elif letter == "V":
        tur.setheading(300)
        tur.pd()
        tur.fd(35)
        tur.left(120)
        tur.fd(35)
        #fixes
        tur.pu()
        tur.right(60)
        tur.fd(15)
    elif letter == "W":
        tur.pd()
        tur.right(60)
        tur.forward(35)
        tur.left(130)
        tur.forward(35)
        tur.right(135)
        tur.forward(35)
        tur.left(130)
        tur.forward(35)
        tur.right(65)
        tur.pu()
        tur.fd(15)
    elif letter == "X":
	tur.pu()
        tur.fd(20)
        tur.right(90)
        tur.fd(30)
        tur.pd()
        tur.left(45)
        tur.fd(20)
        tur.bk(60)
        tur.fd(30)
        tur.left(90)
        tur.fd(30)
        tur.bk(60)
        tur.left(45)
        tur.pu()
        tur.fd(55)
        tur.right(90)
        tur.fd(50)
        tur.fd(15)
    elif letter == "Y":
        tur.setheading(300)
        tur.pd()
        tur.fd(20)
        tur.right(30)
        tur.fd(12)
        tur.left(180)
        tur.fd(12)
        tur.right(30)
        tur.fd(20)
        #fixes
        tur.pu()
        tur.right(60)
        tur.fd(15)
    elif letter == "Z":
        tur.setheading(0)
        tur.pd()
        tur.fd(20)
        tur.right(125)
        tur.fd(35)
        tur.left(125)
        tur.fd(20)
        tur.pu()
        tur.left(90)
        tur.fd(30)
        tur.right(90)
        tur.fd(15)
        
        
        
	    		

        
    elif letter == "Ax":
        # code here
        tur.forward(40)
		
    else:
        turtleLetter("box",tur)
	
2






window = turtle.Screen()
tur = turtle.Turtle()
tur.speed(1)

turtleLetter("F",tur)
turtleLetter("U",tur)
turtleLetter("C",tur)
turtleLetter("C",tur)

window.exitonclick()
